version: '2'
services:
  mysqldb:
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: webshop
      MYSQL_USER: shop
      MYSQL_PASSWORD: shop
    image: mysql/mysql-server:5.7
    restart: always
    ports:
      - 3306:3306
    logging:
      options:
        max-size: 10m
        max-file: '10'
  product_service:
    image: anon767/product_service
    restart: always
    ports:
      - 10001:10000
    logging:
      options:
        max-size: 10m
        max-file: '10'
  category_service:
    image: anon767/category_service
    restart: always
    ports:
      - 10002:10000
    logging:
      options:
        max-size: 10m
        max-file: '10'
  product_category_service:
    image: anon767/product_category_service
    restart: always
    ports:
      - 10003:10000
    logging:
      options:
        max-size: 10m
        max-file: '10'
  discovery_service:
    image: anon767/discovery_service
    restart: always
    ports:
      - 10004:10000
    logging:
      options:
        max-size: 10m
        max-file: '10'

  api_gateway_service:
    image: anon767/api_gateway_service
    restart: always
    ports:
      - 10005:10000
    logging:
      options:
        max-size: 10m
        max-file: '10'
  config_service:
    image: anon767/config_service
    restart: always
    ports:
      - 10006:10000
    logging:
      options:
        max-size: 10m
        max-file: '10'