version: '2.1'
services:
  config-service:
    image: anon767/config_service
    restart: always
    ports:
      - 10006:10000
    logging:
      options:
        max-size: 10m
        max-file: '10'

  product-service:
    image: anon767/product_service
    restart: always
    ports:
      - 10001:10000
    logging:
      options:
        max-size: 10m
        max-file: '10'
    depends_on:
      - config-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10000"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  category-service:
    image: anon767/category_service
    restart: always
    ports:
      - 10002:10000
    logging:
      options:
        max-size: 10m
        max-file: '10'
    depends_on:
      - config-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10000"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  #user-service:
  #  image: anon767/user_service
  #  restart: always
  #  ports:
  #    - 10007:10000
  #  logging:
  #    options:
  #      max-size: 10m
  #      max-file: '10'
  #  depends_on:
  #    - mysqldb
  #    - config-service

#  role-service:
#    image: anon767/role_service
#    restart: always
#    ports:
#      - 10008:10000
#    logging:
#      options:
#        max-size: 10m
#        max-file: '10'
#    depends_on:
#      - mysqldb
#      - config-service

  webshop-ui:
    build:
      context: ./infrastructure_services/webshop-ui/
      dockerfile: ./conf/Dockerfile
    ports:
      - "10009:8080"
    depends_on:
      - product-category-service

  product-category-service:
    image: anon767/product_category_service
    restart: always
    ports:
      - 10003:10000
    logging:
      options:
        max-size: 10m
        max-file: '10'
    depends_on:
      - config-service
      - category-service
      - product-service

  discovery-service:
    image: anon767/discovery_service
    restart: always
    ports:
      - 10004:10000
      - 10090:10008
    logging:
      options:
        max-size: 10m
        max-file: '10'
    depends_on:
      - config-service

  api-gateway-service:
    image: anon767/api_gateway_service
    restart: always
    ports:
      - 10005:10000
      - 10080:10008
    logging:
      options:
        max-size: 10m
        max-file: '10'
    depends_on:
      - config-service

