openapi: 3.0.0
info:
  description: category service
  version: "1.0.0-oas3"
  title: hska webshop API
  contact:
    email: bla@thecout.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: category
    description: Operations available on category entity
paths:
  /category:
    get:
      tags:
        - category
      summary: retrieves all categories
      operationId: getCategories
      description: get all categories
      responses:
        '200':
          description: get all categories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
        '400':
          description: bad input parameter
    post:
      tags:
        - category
      summary: adds an category
      operationId: addCategory
      description: Adds an category to the system
      responses:
        '201':
          description: category created
        '400':
          description: 'invalid input, object invalid'
        '409':
          description: an existing category already exists
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Category'
        description: category item to add
    delete:
      tags:
        - category
      summary: deletes a category
      operationId: deleteCategory
      description: deletes an category from the system
      responses:
        '201':
          description: category deleted
        '400':
          description: 'invalid input, object invalid'
 
components:
  schemas:
    Category:
      required:
        - name
        - id
      properties:
        name:
          type: string
          example: Pets
        id:
          type: integer
          example: 0
