swagger: '2.0'
info:
  description: category service
  version: "1.0.0-oas3"
  title: hska webshop API
  contact:
    email: bla@thecout.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: category
    description: Operations available on category entity
paths:
  /category:
    get:
      tags:
        - category
      summary: retrieves all categories
      operationId: getCategories
      description: get all categories
      produces:
        - application/json
      responses:
        200:
          description: get all categories
          schema:
            type: array
            items:
              $ref: '#/definitions/Category'
        400:
          description: bad input parameter
    post:
      tags:
        - category
      summary: adds an category
      operationId: addCategory
      description: Adds an category to the system
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: category
          description: category item to add
          schema:
            $ref: '#/definitions/Category'
      responses:
        201:
          description: category created
        400:
          description: invalid input, object invalid
        409:
          description: an existing category already exists
    delete:
      tags:
        - category
      summary: deletes a category
      operationId: deleteCategory
      description: deletes an category from the system
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: categoryid
          description: category to delete
          schema:
            type: integer
      responses:
        201:
          description: category deleted
        400:
          description: invalid input, object invalid
definitions:

  Category:
    required:
      - name
      - id
    properties:
      name:
        type: string
        example: Pets
      id:
        type: integer
        example:  0

host: virtserver.swaggerhub.com
basePath: /anon767/HsKA/1.0.0
schemes:
  - https